[package]
name = "vaporwall"
version = "0.1.0"
edition = "2021"

[dependencies]
aya = "0.13"
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
vaporwall-common = { path = "../vaporwall-common", features = ["user"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal", "net"] }
aho-corasick = "1"
